### PR TITLE
Custom Registration Fields

### PR DESCRIPTION
**Pull request by joebochill**
For PXBLUE-1843

#### Changes proposed in this Pull Request:
- Add the ability to inject custom form content into the registration account details flow
- Update docs
- Fix reinitialization of the password screen

#### Screenshots:
image

### CODE REVIEW

**Review by emclaug2 — APPROVED** [review]
Code looks good to me, what you showed in office hours meets all customization requirements imo.

**Comment by jeffvg** [comment]
guess we don't have this?

image

**Comment by joebochill** [comment]
It will technically work, but backgroundColor was missing from the type definition. I just updated that and put out a new beta package for the shared auth.

**Review by jeffvg — APPROVED** [review]
All seems good to me

**Pull request merged**
