### PR TITLE
Publish 2.3.0

### PR DESCRIPTION
**Pull request by daileytj**
Published 2.3.0

waiting for WiFi wiring team
Screen Shot 2021-07-22 at 2 02 11 PM

### CODE REVIEW

**Review by joebochill — APPROVED** [review]
Looks good, just going to need a date adjustment once we get the final word from CRDS

**Review by emclaug2 — APPROVED** [review]

**Comment by jeffvg** [comment]
Anyone else see this for account reg

image

**Comment by jeffvg** [comment]
ignore previous comment...my shared-auth needed update

**Review by jeffvg — APPROVED** [review]
functionality is good

**Pull request merged**
