### PR TITLE
Rebrand Blui

### PR DESCRIPTION
**Pull request by ektasawant**
Fixes 2514 .

### CODE REVIEW

**Review by emclaug2 — APPROVED** [review]

**Comment by jeffvg** [comment]
On a fresh clone, I'm not able to load up the EULA. No errors just doesn't load

image

**Comment by ektasawant** [comment]
> On a fresh clone, I'm not able to load up the EULA. No errors just doesn't load
> 

Master branch screenshot.
> image

Seems it is existing issue. By default it is taking `en_GB` language instead of `en`.

**Comment by emclaug2** [comment]
If this is an existing issue, defaulted to the master branch, could you log an issue for this & we can fix it as part of later release?

**Comment by ektasawant** [comment]
> By default it is taking `en_GB` language instead of `en`.

Logged an issue [93](https://github.com/pxblue/react-workflows/issues/93).

**Review by emclaug2 — APPROVED** [review]

**Pull request merged**
