### PR TITLE
Feature/4595 - Implement show / hide functionality for change password

### PR DESCRIPTION
**Pull request by manojleaton**
Fixes #4595 .

#### Changes proposed in this Pull Request:

- Created ChangePassword component inside components folder of Example project.
- Added types `showChangePasswordDialog` and `setShowChangePasswordDialog` in AppContextType.
- Added a state in App.tsx and passing it to AppContextProvider values to hide and show change password dialog.

#### To Test:

- yarn start:example
- Using useApp hook you can able to access newly added props of AppContextType, in any of the screen.
- You can hide and show the dialog by calling `setShowChangePasswordDialog` prop
Example: 
`    const app = useApp();
      app.setShowChangePasswordDialog(true);
`

#### Any specific feedback you are looking for?

-

### CODE REVIEW

**Review by surajeaton — COMMENTED** [review]
After clicking the next button, is is navigating to login screen.
Instead, it should just hide the dialog.

https://github.com/etn-ccis/blui-react-workflows/assets/120575281/6a5ca42e-3ab1-44c4-a287-c0fa96a77318

**Review by ektaghag-eaton — COMMENTED** [review]
After clicking on Okay button it shows changePassword screen for few seconds and then navigate to login page

Change_PW

**Comment by ektaghag-eaton** [comment]
> After clicking the next button, is is navigating to login screen. Instead, it should just hide the dialog.
> 
>  Screen.Recording.2023-08-31.at.11.21.30.AM.mov

Hi @surajeaton,  after changing the password user should be redirected to the login page so he/she can log in with a new password. Please check the master branch's behaviour `changepasswordDialog` component

master_branch_change_password

**Comment by huayunh** [comment]
After submitting the new password, users should be presented with a success screen before being logged out. See https://github.com/etn-ccis/blui-react-workflows/issues/420

**Comment by JeffGreiner-eaton** [comment]
setting setShowChangePasswordDialog(true) or (false) is working. Guessing this can be implemented anywhere is app?
Also like mentioned from above, there is a pause and a flicker that is re-rendering change password screen.


https://github.com/etn-ccis/blui-react-workflows/assets/119693939/c63fae60-f298-436e-af8f-0a65f000185d

**Comment by manojleaton** [comment]
> setting setShowChangePasswordDialog(true) or (false) is working. Guessing this can be implemented anywhere is app? Also like mentioned from above, there is a pause and a flicker that is re-rendering change password screen.
> 
>  ashowhidedialog.mov

This is fixed, please test

**Review by ektaghag-eaton — COMMENTED** [review]
Build is failing. Please check.
Screenshot 2023-09-04 at 3 57 55 PM

**Review by surajeaton — COMMENTED** [review]
Please resolve the conflicts.

**Review by surajeaton — APPROVED** [review]
Looks good.

**Pull request merged**
