### PR TITLE
[#3] Prepare for release

### PR DESCRIPTION
**Pull request by joebochill**
#### Changes proposed in this Pull Request:
- Update dependencies
- Clean up the example project 
    - this will need another update once this react-auth-workflow package gets published to remove the beta

### CODE REVIEW

**Comment by jeffvg** [comment]
where do we enable customAccountDetails for additional reg info now?

**Comment by joebochill** [comment]
> where do we enable customAccountDetails for additional reg info now?

It still works in the same way, I just removed it from the sample project. I guess I should have probably removed the custom form components themselves too. It is nice to have as an example though so I might put it back in to the demo just commented out.

**Review by jeffvg — APPROVED** [review]
looks good

**Comment by joebochill** [comment]
I put in the custom registration bit, since I suspect that will be the most common customization that teams will do. The boolean props are well documented in the customization docs. And the login screen custom content I would say are going to be less common. If we want to provide examples of that, I would suggest we spend some time next release making more realistic examples.

**Pull request merged**
